{{- if gt (int .Values.replicaCount) 1 -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "warmlogic.fullname" . }}
  labels:
    {{- include "warmlogic.labels" . | nindent 4 }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      {{- include "warmlogic.selectorLabels" . | nindent 6 }}
{{- end }}
