apiVersion: v1
kind: Secret
metadata:
  name: {{ include "warmlogic.fullname" . }}-secrets
  labels:
    {{- include "warmlogic.labels" . | nindent 4 }}
type: Opaque
data:
  WARMLOGIC_AUDIT_KEY: {{ "default-audit-key" | b64enc | quote }}
  WARMLOGIC_API_KEY: {{ "change-me-in-production" | b64enc | quote }}
