# Copyright 2026 espressolee
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
import json
import unittest
from pathlib import Path
from unittest import mock

from warm_logic.kernel import rust_loader
from warm_logic.kernel.ops.audit import IntegrityReport, SovereignAudit
from warm_logic.kernel.substrate.proof_zk import ZKProofGenerator

# Harsh Evaluation: Real Integration Test
# This test strictly FORBIDS mocking of the ZKProofGenerator or Rust Core.
# It proves that the Audit layer can verify REAL proofs generated by the Rust Core.


class TestAuditIntegration(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        if rust_loader.is_simulated():
            raise unittest.SkipTest(
                "Rust Core is simulated (MagicMock). Skipping real integration tests."
            )

    def setUp(self):
        self.db_path = ":memory:"  # Use in-memory SQLite for speed/isolation

        # We still mock the Store class structure, but NOT the logic we are testing.
        # Actually, let's try to verify the ZK logic isolation specifically.
        # We need a minimal environment to run audit._verify_proof_integrity

        self.audit = SovereignAudit(Path("dummy.db"))
        # We mock the STORE connection purely to feed data, NOT the ZK logic
        self.mock_store = mock.Mock()
        self.mock_conn = mock.Mock()
        self.audit.store = self.mock_store
        self.mock_store.conn = self.mock_conn

    def test_real_zk_verification_loop(self):
        """
        FAIL-PROOF INTEGRATION:
        1. Generate a REAL proof using Rust.
        2. Feed it to the Audit layer.
        3. Verify Audit accepts it WITHOUT mocks.
        """
        print("\n[Harsh Audit] Generating REAL Rust Bulletproof...")

        # 1. Generate Real Proof
        prev = "0" * 64
        txs = ["tx1", "tx2"]
        # We need a valid 'new' root that matches the commitment logic, or simply
        # rely on the fact that generate_proof creates a valid proof for *whatever* input.
        # The verification checks consistency of inputs against the proof.

        # Compute expected roots first to ensure consistency if the verifier checks them
        # (The current ZKProofGenerator.verify_proof checks if the proof PROVES the commitment
        # derived from (prev, txs, new). So inputs must match.)

        # We need the commitment logic from ZKProofGenerator to calculate 'new'?
        # No, generate_proof takes (prev, txs, new).
        # The Rust side proves: "I know a value v such that commitment(v) == C".
        # In our simplified Bulletproof implementation (range proof), 'v' is derived from the commitment hash.
        # So we just need consistent strings.

        new_root = "block_hash"

        try:
            proof_json = ZKProofGenerator.generate_proof(prev, txs, new_root)
        except RuntimeError as e:
            self.fail(f"Rust Core Generation Failed: {e}")

        print("[Harsh Audit] Proof Generated. Size:", len(proof_json))

        # 2. Setup Audit Input
        # Audit iterates blocks. We feed it a block containing this valid proof.
        block_row = {
            "hash": new_root,
            "prev_hash": prev,
            "tx_ids": json.dumps(txs),  # stored as JSON string in DB
            "zk_proof": proof_json,
        }

        # We mock the DB return to provide this REAL data
        self.mock_conn.execute.return_value.fetchall.return_value = [block_row]

        # 3. Execution (NO MOCKS on ZKProofGenerator)
        report = IntegrityReport()
        result = self.audit._verify_proof_integrity(report)

        # 4. Strict Assertion
        self.assertTrue(
            result, f"Audit failed to verify real proof! Details: {report.details}"
        )
        print("[Harsh Audit] SUCCESS: Real Rust Proof verified by Python Audit Layer.")

    def test_tampered_proof_rejection(self):
        """
        Verify that the real Rust engine correctly REJECTS a modified proof.
        """
        # 1. Generate Valid Proof
        proof_json = ZKProofGenerator.generate_proof("a", ["b"], "c")
        proof_obj = json.loads(proof_json)

        # 2. Tamper with it (bitflip in proof hex)
        # We assume proof_hex is long enough.
        orig_proof = proof_obj["proof"]
        # rudimentary tamper: replace last char
        tampered_proof_hex = orig_proof[:-1] + ("0" if orig_proof[-1] != "0" else "1")
        proof_obj["proof"] = tampered_proof_hex

        tampered_json = json.dumps(proof_obj)

        # 3. Feed to Audit
        block_row = {
            "hash": "bad_block",
            "prev_hash": "a",
            "tx_ids": json.dumps(["b"]),
            "zk_proof": tampered_json,
        }
        self.mock_conn.execute.return_value.fetchall.return_value = [block_row]

        # 4. Verify Rejection
        report = IntegrityReport()
        result = self.audit._verify_proof_integrity(report)

        self.assertFalse(result, "Audit ACCEPTED a tampered proof! CRITICAL FAILURE.")
        self.assertIn("ZK-Proof INVALID", report.details[0])

    def test_atomic_truth_path(self):
        """
        Verify the Atomic Truth (Rust Sled Recursion) path.
        """
        print("\n[Harsh Audit] Testing Atomic Truth Path...")
        # 1. Enable Rust Mode on Mock
        self.audit.store._use_rust = True

        # 2. Setup Real Proof Data
        prev = "0" * 64
        txs = ["tx_atomic"]
        zk_proof = ZKProofGenerator.generate_proof(prev, txs, "h_atomic")

        block = {
            "hash": "h_atomic",
            "prev_hash": prev,
            "tx_ids": txs,  # Rust Sled returns list, not JSON str
            "zk_proof": zk_proof,
            "miner": "rust_miner",
            "timestamp": 12345.0,
        }

        # 3. Mock Sled Responses
        self.mock_store.get_last_block.return_value = block
        self.mock_store.get_block.side_effect = lambda h: (
            block if h == "h_atomic" else None
        )

        # 4. Run Audit
        report = IntegrityReport()
        result = self.audit._run_atomic_truth_audit(report)

        self.assertTrue(result, f"Atomic Truth Audit Failed! Details: {report.details}")
        print("[Harsh Audit] SUCCESS: Atomic Truth (Sled) recursion verified.")


if __name__ == "__main__":
    unittest.main()
