#!/usr/bin/env python3
"""Detect obvious accidental agent-literal markers in source files."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]

# Keep this list narrow to avoid false positives on legitimate "codex" symbols.
DISALLOWED_PATTERNS = (
    re.compile(r"generated by codex", re.IGNORECASE),
    re.compile(r"codex[ _-]?artifact", re.IGNORECASE),
    re.compile(r"claude code generated", re.IGNORECASE),
    re.compile(r"do not edit[, ]+ai generated", re.IGNORECASE),
)

SCAN_SUFFIXES = {
    ".py",
    ".rs",
    ".toml",
    ".md",
    ".txt",
    ".yml",
    ".yaml",
    ".json",
    ".sh",
    ".ts",
    ".tsx",
    ".js",
    ".jsx",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--dirs", required=True, help="Comma-separated directories")
    parser.add_argument(
        "--soft",
        type=int,
        default=0,
        help="Soft mode (1 = always exit 0, still print findings)",
    )
    return parser.parse_args()


def iter_files(target: Path):
    for path in target.rglob("*"):
        if not path.is_file():
            continue
        if path.suffix.lower() not in SCAN_SUFFIXES:
            continue
        yield path


def find_hits(path: Path) -> list[str]:
    rel = path.relative_to(ROOT).as_posix()
    if rel == "scripts/ci/check_codex_literals.py":
        return []
    hits: list[str] = []
    try:
        lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
    except OSError:
        return hits

    for idx, line in enumerate(lines, start=1):
        for pat in DISALLOWED_PATTERNS:
            if pat.search(line):
                hits.append(f"{rel}:{idx}:{line.strip()[:160]}")
                break
    return hits


def main() -> int:
    args = parse_args()
    targets = [d.strip() for d in args.dirs.split(",") if d.strip()]
    if not targets:
        print("[CODEX-LITERAL] ERROR: no target dirs provided")
        return 2

    all_hits: list[str] = []
    scanned_files = 0
    for rel_dir in targets:
        target = ROOT / rel_dir
        if not target.exists():
            print(f"[CODEX-LITERAL] WARN: missing target dir {rel_dir}")
            continue
        for file_path in iter_files(target):
            scanned_files += 1
            all_hits.extend(find_hits(file_path))

    if all_hits:
        status = "SOFT-FAIL" if args.soft else "FAIL"
        print(
            f"[CODEX-LITERAL] {status}: findings={len(all_hits)} "
            f"scanned_files={scanned_files}"
        )
        for hit in all_hits[:200]:
            print(f"  - {hit}")
        return 0 if args.soft else 1

    print(f"[CODEX-LITERAL] OK: findings=0 scanned_files={scanned_files}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
