# Copyright 2026 espressolee
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
from pathlib import Path

from warm_logic.kernel.intelligence.auto_tasker import AutoTasker
from warm_logic.kernel.intelligence.knowledge_graph import KnowledgeGraph
from warm_logic.kernel.intelligence.researcher import WebResearcher
from warm_logic.kernel.intelligence.self_critique import SelfCritique


class IntelligenceLoop:
    """
    The "Master Mind" that coordinates autonomous task discovery,
    self-critique, and knowledge mapping.
    """

    def __init__(self, root_dir: str, artifact_dir: str):
        self.root_dir = Path(root_dir)
        self.artifact_dir = Path(artifact_dir)
        self.kg_path = self.root_dir / "knowledge_graph.json"
        self.walkthrough_path = self.artifact_dir / "walkthrough.md"
        self.roadmap_path = self.artifact_dir / "AGI_10_10_ROADMAP.md"

    def run_tick(self):
        """Execute one cycle of the intelligence loop."""
        print("[Intelligence] Running project-wide audit...")

        # 1. Update Knowledge Graph
        kg = KnowledgeGraph(str(self.root_dir))
        kg.scan()
        kg.save(str(self.kg_path))

        # 2. Perform Self-Critique
        critique = SelfCritique(str(self.walkthrough_path))
        report = critique.generate_report()

        # 3. Discover Next Tasks
        tasker = AutoTasker(str(self.kg_path), str(self.roadmap_path))
        suggestion = tasker.suggest_next_mission()

        # 4. Web Research (if needed)
        if suggestion.get("action", "").startswith("research_web"):
            researcher = WebResearcher()
            topic = suggestion["action"].replace("research_web: ", "")
            print(f"[Intelligence] Conducting web research on: {topic}")
            research_res = researcher.research_topic(topic)
            suggestion["research_context"] = research_res

        # 5. Consolidate and Update Task.md
        self._generate_evolution_report(report, suggestion)

    def _generate_evolution_report(self, critique_report: str, suggestion: dict):
        report_path = self.artifact_dir / "EVOLUTION_REPORT.md"

        research_section = ""
        if "research_context" in suggestion:
            research_section = f"""
## 🌐 Research Insight
{suggestion["research_context"]}
"""

        content = f"""# 🧬 WarmLogic Evolution Report

## 🧐 Self-Critique (The Brutal Truth)
{critique_report}
{research_section}
## 🎯 Next Mission (The Strategic Move)
- **Goal**: {suggestion["suggestion"]}
- **Impact**: {suggestion["impact"]}
- **Action**: {suggestion["action"]}

---
*Report generated by IntelligenceLoop v1.0*
"""
        report_path.write_text(content)
        print(f"[Intelligence] Evolution report saved to {report_path}")


if __name__ == "__main__":
    import os

    # GOV-003: Use environment variables for path neutrality
    ROOT = os.environ.get("WARMLOGIC_ROOT", ".")
    ARTIFACTS = os.environ.get("WARMLOGIC_ARTIFACTS", "./artifacts")

    loop = IntelligenceLoop(ROOT, ARTIFACTS)
    loop.run_tick()
