from typing import Any, List, Optional, Tuple

def verify(public_key: str, message: str, signature: str) -> bool: ...
def get_balance(address: str) -> int: ...
def get_state_root() -> str: ...

class SovereignStore:
    def __init__(self, path: str) -> None: ...
    def get_all(self) -> List[Tuple[str, str]]: ...
    def put(self, key: str, val: str) -> None: ...
    def get(self, key: str) -> Optional[str]: ...
    def get_block(self, hash: str) -> Optional[Any]: ...
    def get_last_block(self) -> Optional[Any]: ...
    def get_last_event(self) -> Optional[Any]: ...

class RustRoutingTable:
    def __init__(self, local_id: List[int]) -> None: ...
    def update(self, node_id: List[int], address: str, port: int) -> None: ...
    def find_closest(
        self, target_id: List[int]
    ) -> List[Tuple[List[int], str, int]]: ...

class RustyDiscoveryAgent:
    def __init__(
        self, target_id: List[int], initial_peers: List[Tuple[List[int], str, int]]
    ) -> None: ...
    def add_response(self, peers: List[Tuple[List[int], str, int]]) -> None: ...
    def mark_queried(self, node_id: List[int]) -> None: ...
    def mark_failed(self, node_id: List[int]) -> None: ...
    def get_next_peers(self) -> List[Tuple[List[int], str, int]]: ...
    def is_finished(self) -> bool: ...
    def get_k_closest(self) -> List[Tuple[List[int], str, int]]: ...
