package sovereign

/*
#cgo LDFLAGS: -L../../../rust_core/target/release -lwarm_logic_rs
#include <stdlib.h>
#include <stdbool.h>

// Manually defining signatures that would be generated by cbindgen
typedef struct {
    char* public_key;
    char* private_key;
} PQCKeypair;

// Note: These would be exported by the Rust lib
// char* wasm_sign(const char* sk, const char* msg);
// bool wasm_verify(const char* pk, const char* msg, const char* sig);
*/
import "C"

// import "unsafe"

// ffi.go handles the raw boundary between Go and Rust.
// In this phase, we use internal mock logic if the .so/.dylib is missing,
// but the CGO structure is ready for the "Hardened" link.
