apiVersion: v1
kind: Namespace
metadata:
  name: warmlogic-production
  labels:
    app: warmlogic
    environment: production
    era: "4000"
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
